### ISSUE TITLE
errors during build

### ISSUE THREAD

**Issue by ttodua** [Anonym0ose/JitDumper#6]
Thanks for the repo.
I have issues when build: 
for x64 : https://imgsh.net/i/KpAZrps.png
for x86 : https://imgsh.net/a/G7CGIBd.png

any clues? i had targeted 10.0.22621.0 correctly.

also, please if you can upload the built/compiled files under https://github.com/Anonym0ose/JitDumper/releases

**Comment by Anonym0ose** [comment]
Just pushed something I committed last October, let me know if you still cannot build it. 

I will not be uploading any prebuilt binaries as they would not work for all .net versions and architectures.

**Comment by ttodua** [comment]
Many thanks for update. side-question: do you have any contact (discord/mail/tg) where I can PM you about specific code?

**Comment by ttodua** [comment]
side-note: i cant see any push/update here. maybe you committed locally and forgot to push?
